Repository ministryofjustice/hmpps-book-secure-move-frontend, pull requests merged in 2019-09, with the labels that each got.

#218 Ensure session is destroyed before redirecting
  app/auth/controllers.js
  app/auth/controllers.test.js
Labels: bug

#244 Update major dependencies
  package-lock.json
  package.json
Labels: multipart

#245 Update sass loader dependency
  package-lock.json
  package.json
  webpack.config.js
Labels: multipart

#246 Update connect redis dependency
  config/redis-store.js
  config/redis-store.test.js
  package-lock.json
  package.json
Labels: multipart

#241 [P4-367] Cache reference data from API
  common/lib/api-client/index.js
  common/lib/api-client/index.test.js
  common/lib/api-client/middleware/index.js
  common/lib/api-client/middleware/request.js
  common/lib/api-client/middleware/request.test.js
  common/lib/api-client/models.js
  common/lib/api-client/models.test.js
  config/index.js
  config/redis-store.js
  config/redis-store.test.js
  package-lock.json
  package.json
  server.js
Labels: wip
