Repository ministryofjustice/hmpps-book-secure-move-frontend, pull requests merged in 2020-12, with the labels that each got.

#1071 [IM-18] [P4-2415] Handle Unprocessable entities
  app/move/controllers/assign/save.js
  app/move/controllers/assign/save.test.js
  app/move/controllers/create/save.js
  app/move/controllers/create/save.test.js
  app/move/controllers/review.js
  app/move/controllers/review.test.js
  app/move/controllers/unassign.js
  app/move/controllers/unassign.test.js
  app/move/controllers/update/base.js
  app/move/controllers/update/base.test.js
  app/move/views/assign/assign-conflict.njk
  app/move/views/assign/no-special-vehicle.njk
  app/move/views/create/save-conflict.njk
  app/move/views/unassign-ineligible.njk
  common/templates/action-prevented.njk
  common/templates/layouts/action-prevented.njk
  locales/en/validation.json
Labels: blocked

#1096 Show important event flags on profile and dashboard [P4 2506]
  app/move/controllers/timeline.js
  app/move/controllers/timeline.test.js
  app/move/controllers/view/view.locals.js
  app/move/controllers/view/view.locals.test.js
  app/move/views/view.njk
  common/components/card/card.yaml
  common/components/card/template.njk
  common/components/card/template.test.js
  common/components/tag/_tag.scss
  common/components/tag/tag.yaml
  common/components/tag/template.njk
  common/components/tag/template.test.js
  common/components/timeline/_timeline.scss
  common/components/timeline/template.njk
  common/helpers/events/get-container-classes.js
  common/helpers/events/get-container-classes.test.js
  common/helpers/events/get-description.js
  common/helpers/events/get-description.test.js
  common/helpers/events/get-event-classification.js
  common/helpers/events/get-event-classification.test.js
  common/helpers/events/get-flag.js
  common/helpers/events/get-flag.test.js
  common/helpers/events/get-header-classes.js
  common/helpers/events/get-header-classes.test.js
  common/helpers/events/get-heading.js
  common/helpers/events/get-heading.test.js
  common/helpers/events/get-label-classes.js
  common/helpers/events/get-label-classes.test.js
  common/helpers/events/index.js
  common/lib/api-client/models/event.js
  common/lib/api-client/models/move.js
  common/lib/api-client/transformers/move.transformer.js
  common/lib/api-client/transformers/move.transformer.test.js
  common/presenters/event-to-tag-component.js
  common/presenters/event-to-tag-component.test.js
  common/presenters/event-to-timeline-item-component.js
  common/presenters/event-to-timeline-item-component.test.js
  common/presenters/events-to-timeline-component.js
  common/presenters/events-to-timeline-component.test.js
  common/presenters/index.js
  common/presenters/move-to-card-component.js
  common/presenters/move-to-card-component.test.js
  common/presenters/move-to-important-events-tag-list-component.js
  common/presenters/move-to-important-events-tag-list-component.test.js
  common/presenters/move-to-timeline-component.js
  common/presenters/move-to-timeline-component.test.js
  common/presenters/profile-to-card-component.js
  common/presenters/profile-to-card-component.test.js
  common/services/move.js
  common/services/move.test.js
  locales/en/events.json
  test/fixtures/api-client/move.find.json
  test/fixtures/api-client/move.findAll.json
Labels: blocked, do not merge

#1135 refactor: API client user header and support for custom header config
  common/lib/api-client/index.js
  common/lib/api-client/index.test.js
  common/lib/api-client/middleware/request-headers.js
  common/lib/api-client/middleware/request-headers.test.js
  common/lib/api-client/request-headers.js
  common/lib/api-client/request-headers.test.js
Labels: do not merge
